---
- name:  Windows Update
  hosts: all
  connection: winrm
  gather_facts: false
  tasks:
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates' , 'FeaturePacks']
        reboot: yes
        reboot_timeout: 600




